
import 'package:flutter/material.dart';
import 'package:child_game/utils/alphabet_data.dart';

final List<AlphabetItem> hindiAlphabetData = [
  AlphabetItem(letter: "अ", word: "Anar (Pomegranate)", audioText: "अनार", icon: "🍎", color: Colors.red),
  AlphabetItem(letter: "आ", word: "Aam (Mango)", audioText: "आम", icon: "🥭", color: Colors.orange),
  AlphabetItem(letter: "इ", word: "Imli (Tamarind)", audioText: "इमली", icon: "🫘", color: Colors.brown),
  AlphabetItem(letter: "ई", word: "Eekh (Sugarcane)", audioText: "ईख", icon: "🎋", color: Colors.green),
  AlphabetItem(letter: "उ", word: "Ullu (Owl)", audioText: "उल्लू", icon: "🦉", color: Colors.brown),
  AlphabetItem(letter: "ऊ", word: "Oon (Wool)", audioText: "ऊन", icon: "🧶", color: Colors.purple),
  AlphabetItem(letter: "ऋ", word: "Rishi (Sage)", audioText: "ऋषि", icon: "🧘", color: Colors.orange),
  AlphabetItem(letter: "ए", word: "Edi (Heel)", audioText: "एड़ी", icon: "🦶", color: Colors.deepOrangeAccent),
  AlphabetItem(letter: "ऐ", word: "Ainak (Spectacles)", audioText: "ऐनक", icon: "👓", color: Colors.blue),
  AlphabetItem(letter: "ओ", word: "Okhli (Mortar)", audioText: "ओखली", icon: "🥣", color: Colors.grey),
  AlphabetItem(letter: "औ", word: "Aurat (Woman)", audioText: "औरत", icon: "👩", color: Colors.pink),
  AlphabetItem(letter: "अं", word: "Angoor (Grapes)", audioText: "अंगूर", icon: "🍇", color: Colors.purple),
  AlphabetItem(letter: "अः", word: "Ahah", audioText: "अः", icon: "😲", color: Colors.grey),
  AlphabetItem(letter: "क", word: "Kabutar (Pigeon)", audioText: "कबूतर", icon: "🐦", color: Colors.blueGrey),
  AlphabetItem(letter: "ख", word: "Khargosh (Rabbit)", audioText: "खरगोश", icon: "🐰", color: Colors.deepOrange),
  AlphabetItem(letter: "ग", word: "Gamla (Flower Pot)", audioText: "गमला", icon: "🪴", color: Colors.green),
  AlphabetItem(letter: "घ", word: "Ghadi (Watch)", audioText: "घड़ी", icon: "🕰️", color: Colors.brown),
  AlphabetItem(letter: "ङ", word: "Anga", audioText: "ङ", icon: "😶", color: Colors.grey),
  AlphabetItem(letter: "च", word: "Chammach (Spoon)", audioText: "चम्मच", icon: "🥄", color: Colors.grey),
  AlphabetItem(letter: "छ", word: "Chhatri (Umbrella)", audioText: "छतरी", icon: "☂️", color: Colors.blue),
  AlphabetItem(letter: "ज", word: "Jahaj (Ship)", audioText: "जहाज़", icon: "🚢", color: Colors.blueAccent),
  AlphabetItem(letter: "झ", word: "Jhanda (Flag)", audioText: "झंडा", icon: "🇮🇳", color: Colors.orange),
  AlphabetItem(letter: "ञ", word: "Iya", audioText: "ञ", icon: "🙂", color: Colors.grey),
  AlphabetItem(letter: "ट", word: "Tamatar (Tomato)", audioText: "टमाटर", icon: "🍅", color: Colors.red),
  AlphabetItem(letter: "ठ", word: "Thathera (Smith)", audioText: "ठठेरा", icon: "🔨", color: Colors.brown),
  AlphabetItem(letter: "ड", word: "Damru (Drum)", audioText: "डमरू", icon: "🥁", color: Colors.orange),
  AlphabetItem(letter: "ढ", word: "Dhakkan (Lid)", audioText: "ढक्कन", icon: "🥘", color: Colors.grey),
  AlphabetItem(letter: "ण", word: "Ana", audioText: "ण", icon: "😶", color: Colors.grey),
  AlphabetItem(letter: "त", word: "Tarbooj (Watermelon)", audioText: "तरबूज", icon: "🍉", color: Colors.green),
  AlphabetItem(letter: "थ", word: "Tharmas (Flask)", audioText: "थर्मस", icon: "🍶", color: Colors.blue),
  AlphabetItem(letter: "द", word: "Dawaat (Ink Pot)", audioText: "दवात", icon: "✒️", color: Colors.indigo),
  AlphabetItem(letter: "ध", word: "Dhanush (Bow)", audioText: "धनुष", icon: "🏹", color: Colors.brown),
  AlphabetItem(letter: "न", word: "Nul (Tap)", audioText: "नल", icon: "🚰", color: Colors.grey),
  AlphabetItem(letter: "प", word: "Patang (Kite)", audioText: "पतंग", icon: "🪁", color: Colors.pink),
  AlphabetItem(letter: "फ", word: "Phal (Fruit)", audioText: "फल", icon: "🍎", color: Colors.green),
  AlphabetItem(letter: "ब", word: "Bakri (Goat)", audioText: "बकरी", icon: "🐐", color: Colors.brown),
  AlphabetItem(letter: "भ", word: "Bhalu (Bear)", audioText: "भालू", icon: "🐻", color: Colors.brown),
  AlphabetItem(letter: "म", word: "Machhli (Fish)", audioText: "मछली", icon: "🐟", color: Colors.blue),
  AlphabetItem(letter: "य", word: "Yagya (Ritual)", audioText: "यज्ञ", icon: "🔥", color: Colors.orange),
  AlphabetItem(letter: "र", word: "Rath (Chariot)", audioText: "रथ", icon: "🐎", color: Colors.brown),
  AlphabetItem(letter: "ल", word: "Lattu (Top)", audioText: "लट्टू", icon: "🌪️", color: Colors.purple),
  AlphabetItem(letter: "व", word: "Vak (Crane)", audioText: "वक", icon: "🦢", color: Colors.blueGrey),
  AlphabetItem(letter: "श", word: "Shalgam (Turnip)", audioText: "शलगम", icon: "🧅", color: Colors.purpleAccent),
  AlphabetItem(letter: "ष", word: "Shatkon (Hexagon)", audioText: "षट्कोण", icon: "🛑", color: Colors.red),
  AlphabetItem(letter: "स", word: "Santra (Orange)", audioText: "संतरा", icon: "🍊", color: Colors.orange),
  AlphabetItem(letter: "ह", word: "Haathi (Elephant)", audioText: "हाथी", icon: "🐘", color: Colors.grey),
  AlphabetItem(letter: "क्ष", word: "Kshatriya (Warrior)", audioText: "क्षत्रिय", icon: "⚔️", color: Colors.orange),
  AlphabetItem(letter: "त्र", word: "Trishul (Trident)", audioText: "त्रिशूल", icon: "🔱", color: Colors.black),
  AlphabetItem(letter: "ज्ञ", word: "Gyani (Wise)", audioText: "ज्ञानी", icon: "🧘", color: Colors.orange),
];
