const GameData = {
    alphabet: [
        { text: "A", icon: "🍎", name: "Apple", color: "#F44336" },
        { text: "B", icon: "⚽", name: "Ball", color: "#2196F3" },
        { text: "C", icon: "🚗", name: "Car", color: "#FF9800" },
        { text: "D", icon: "🦆", name: "Duck", color: "#4CAF50" },
        { text: "E", icon: "🐘", name: "Elephant", color: "#9E9E9E" },
        { text: "F", icon: "🐟", name: "Fish", color: "#448AFF" },
        { text: "G", icon: "🍇", name: "Grapes", color: "#9C27B0" },
        { text: "H", icon: "🏠", name: "House", color: "#795548" },
        { text: "I", icon: "🍦", name: "Ice Cream", color: "#E91E63" },
        { text: "J", icon: "🥤", name: "Juice", color: "#FFAB40" },
        { text: "K", icon: "🪁", name: "Kite", color: "#009688" },
        { text: "L", icon: "🦁", name: "Lion", color: "#FF9800" },
        { text: "M", icon: "🐵", name: "Monkey", color: "#795548" },
        { text: "N", icon: "👃", name: "Nose", color: "#FF5722" },
        { text: "O", icon: "🐙", name: "Octopus", color: "#673AB7" },
        { text: "P", icon: "🐧", name: "Penguin", color: "#000000" },
        { text: "Q", icon: "👑", name: "Queen", color: "#FFC107" },
        { text: "R", icon: "🐰", name: "Rabbit", color: "#9E9E9E" },
        { text: "S", icon: "☀️", name: "Sun", color: "#FF9800" },
        { text: "T", icon: "🐯", name: "Tiger", color: "#FFAB40" },
        { text: "U", icon: "☂️", name: "Umbrella", color: "#2196F3" },
        { text: "V", icon: "🎻", name: "Violin", color: "#795548" },
        { text: "W", icon: "🐳", name: "Whale", color: "#2196F3" },
        { text: "X", icon: "🎹", name: "Xylophone", color: "#F44336" },
        { text: "Y", icon: "🛥️", name: "Yacht", color: "#607D8B" },
        { text: "Z", icon: "🦓", name: "Zebra", color: "#000000" }
    ],
    animals: [
        { text: "Dog", icon: "🐶", name: "Dog", color: "#795548" },
        { text: "Cat", icon: "🐱", name: "Cat", color: "#FF9800" },
        { text: "Mouse", icon: "🐭", name: "Mouse", color: "#9E9E9E" },
        { text: "Hamster", icon: "🐹", name: "Hamster", color: "#FFAB40" },
        { text: "Rabbit", icon: "🐰", name: "Rabbit", color: "#E91E63" },
        { text: "Fox", icon: "🦊", name: "Fox", color: "#FF5722" },
        { text: "Bear", icon: "🐻", name: "Bear", color: "#795548" },
        { text: "Panda", icon: "🐼", name: "Panda", color: "#000000" },
        { text: "Tiger", icon: "🐯", name: "Tiger", color: "#FF9800" },
        { text: "Lion", icon: "🦁", name: "Lion", color: "#FFAB40" },
        { text: "Cow", icon: "🐮", name: "Cow", color: "#000000" },
        { text: "Pig", icon: "🐷", name: "Pig", color: "#FF4081" },
        { text: "Frog", icon: "🐸", name: "Frog", color: "#4CAF50" },
        { text: "Monkey", icon: "🐵", name: "Monkey", color: "#795548" },
        { text: "Chicken", icon: "🐔", name: "Chicken", color: "#F44336" },
        { text: "Penguin", icon: "🐧", name: "Penguin", color: "#000000" },
        { text: "Owl", icon: "🦉", name: "Owl", color: "#795548" },
        { text: "Turtle", icon: "🐢", name: "Turtle", color: "#4CAF50" },
        { text: "Snake", icon: "🐍", name: "Snake", color: "#4CAF50" },
        { text: "Octopus", icon: "🐙", name: "Octopus", color: "#9C27B0" },
        { text: "Whale", icon: "🐳", name: "Whale", color: "#2196F3" },
        { text: "Shark", icon: "🦈", name: "Shark", color: "#9E9E9E" },
        { text: "Giraffe", icon: "🦒", name: "Giraffe", color: "#FF9800" },
        { text: "Elephant", icon: "🐘", name: "Elephant", color: "#9E9E9E" },
        { text: "Koala", icon: "🐨", name: "Koala", color: "#9E9E9E" }
    ],
    fruits: [
        { text: "Apple", icon: "🍎", name: "Apple", color: "#F44336" },
        { text: "Pear", icon: "🍐", name: "Pear", color: "#B2FF59" },
        { text: "Orange", icon: "🍊", name: "Orange", color: "#FF9800" },
        { text: "Lemon", icon: "🍋", name: "Lemon", color: "#FFEB3B" },
        { text: "Banana", icon: "🍌", name: "Banana", color: "#FFEB3B" },
        { text: "Watermelon", icon: "🍉", name: "Watermelon", color: "#4CAF50" },
        { text: "Grapes", icon: "🍇", name: "Grapes", color: "#9C27B0" },
        { text: "Strawberry", icon: "🍓", name: "Strawberry", color: "#F44336" },
        { text: "Blueberry", icon: "🫐", name: "Blueberry", color: "#2196F3" },
        { text: "Cherry", icon: "🍒", name: "Cherry", color: "#F44336" },
        { text: "Mango", icon: "🥭", name: "Mango", color: "#FF9800" },
        { text: "Pineapple", icon: "🍍", name: "Pineapple", color: "#FFC107" },
        { text: "Coconut", icon: "🥥", name: "Coconut", color: "#795548" },
        { text: "Kiwi", icon: "🥝", name: "Kiwi", color: "#4CAF50" },
        { text: "Potato", icon: "🥔", name: "Potato", color: "#795548" },
        { text: "Carrot", icon: "🥕", name: "Carrot", color: "#FF9800" },
        { text: "Corn", icon: "🌽", name: "Corn", color: "#FFEB3B" },
        { text: "Pizza", icon: "🍕", name: "Pizza", color: "#FF9800" },
        { text: "Burger", icon: "🍔", name: "Hamburger", color: "#FF9800" },
        { text: "Ice Cream", icon: "🍦", name: "Ice Cream", color: "#E91E63" },
        { text: "Cake", icon: "🎂", name: "Cake", color: "#E91E63" },
        { text: "Donut", icon: "🍩", name: "Donut", color: "#795548" },
        { text: "Cookie", icon: "🍪", name: "Cookie", color: "#795548" },
        { text: "Honey", icon: "🍯", name: "Honey", color: "#FFC107" },
        { text: "Milk", icon: "🥛", name: "Milk", color: "#FFFFFF" }
    ],
    hindi: [
        { text: "अ", icon: "🍎", name: "Anar (Pomegranate)", audioText: "अनार", color: "#F44336" },
        { text: "आ", icon: "🥭", name: "Aam (Mango)", audioText: "आम", color: "#FF9800" },
        { text: "इ", icon: "🫘", name: "Imli (Tamarind)", audioText: "इमली", color: "#795548" },
        { text: "ई", icon: "🎋", name: "Eekh (Sugarcane)", audioText: "ईख", color: "#4CAF50" },
        { text: "उ", icon: "🦉", name: "Ullu (Owl)", audioText: "उल्लू", color: "#795548" },
        { text: "ऊ", icon: "🧶", name: "Oon (Wool)", audioText: "ऊन", color: "#9C27B0" },
        { text: "ऋ", icon: "🧘", name: "Rishi (Sage)", audioText: "ऋषि", color: "#FF9800" },
        { text: "ए", icon: "🦶", name: "Edi (Heel)", audioText: "एड़ी", color: "#FF6E40" },
        { text: "ऐ", icon: "👓", name: "Ainak (Spectacles)", audioText: "ऐनक", color: "#2196F3" },
        { text: "ओ", icon: "🥣", name: "Okhli (Mortar)", audioText: "ओखली", color: "#9E9E9E" },
        { text: "औ", icon: "👩", name: "Aurat (Woman)", audioText: "औरत", color: "#E91E63" },
        { text: "अं", icon: "🍇", name: "Angoor (Grapes)", audioText: "अंगूर", color: "#9C27B0" },
        { text: "अः", icon: "😲", name: "Ahah", audioText: "अः", color: "#9E9E9E" },
        { text: "क", icon: "🐦", name: "Kabutar (Pigeon)", audioText: "कबूतर", color: "#607D8B" },
        { text: "ख", icon: "🐰", name: "Khargosh (Rabbit)", audioText: "खरगोश", color: "#FF5722" },
        { text: "ग", icon: "🪴", name: "Gamla (Flower Pot)", audioText: "गमला", color: "#4CAF50" },
        { text: "घ", icon: "🕰️", name: "Ghadi (Watch)", audioText: "घड़ी", color: "#795548" },
        { text: "ङ", icon: "😶", name: "Anga", audioText: "ङ", color: "#9E9E9E" },
        { text: "च", icon: "🥄", name: "Chammach (Spoon)", audioText: "चम्मच", color: "#9E9E9E" },
        { text: "छ", icon: "☂️", name: "Chhatri (Umbrella)", audioText: "छतरी", color: "#2196F3" },
        { text: "ज", icon: "🚢", name: "Jahaj (Ship)", audioText: "जहाज़", color: "#448AFF" },
        { text: "झ", icon: "🇮🇳", name: "Jhanda (Flag)", audioText: "झंडा", color: "#FF9800" },
        { text: "ञ", icon: "🙂", name: "Iya", audioText: "ञ", color: "#9E9E9E" },
        { text: "ट", icon: "🍅", name: "Tamatar (Tomato)", audioText: "टमाटर", color: "#F44336" },
        { text: "ठ", icon: "🔨", name: "Thathera (Smith)", audioText: "ठठेरा", color: "#795548" },
        { text: "ड", icon: "🥁", name: "Damru (Drum)", audioText: "डमरू", color: "#FF9800" },
        { text: "ढ", icon: "🥘", name: "Dhakkan (Lid)", audioText: "ढक्कन", color: "#9E9E9E" },
        { text: "ण", icon: "😶", name: "Ana", audioText: "ण", color: "#9E9E9E" },
        { text: "त", icon: "🍉", name: "Tarbooj (Watermelon)", audioText: "तरबूज", color: "#4CAF50" },
        { text: "थ", icon: "🍶", name: "Tharmas (Flask)", audioText: "थर्मस", color: "#2196F3" },
        { text: "द", icon: "✒️", name: "Dawaat (Ink Pot)", audioText: "दवात", color: "#3F51B5" },
        { text: "ध", icon: "🏹", name: "Dhanush (Bow)", audioText: "धनुष", color: "#795548" },
        { text: "न", icon: "🚰", name: "Nul (Tap)", audioText: "नल", color: "#9E9E9E" },
        { text: "प", icon: "🪁", name: "Patang (Kite)", audioText: "पतंग", color: "#E91E63" },
        { text: "फ", icon: "🍎", name: "Phal (Fruit)", audioText: "फल", color: "#4CAF50" },
        { text: "ब", icon: "🐐", name: "Bakri (Goat)", audioText: "बकरी", color: "#795548" },
        { text: "भ", icon: "🐻", name: "Bhalu (Bear)", audioText: "भालू", color: "#795548" },
        { text: "म", icon: "🐟", name: "Machhli (Fish)", audioText: "मछली", color: "#2196F3" },
        { text: "य", icon: "🔥", name: "Yagya (Ritual)", audioText: "यज्ञ", color: "#FF9800" },
        { text: "र", icon: "🐎", name: "Rath (Chariot)", audioText: "रथ", color: "#795548" },
        { text: "ल", icon: "🌪️", name: "Lattu (Top)", audioText: "लट्टू", color: "#9C27B0" },
        { text: "व", icon: "🦢", name: "Vak (Crane)", audioText: "वक", color: "#607D8B" },
        { text: "श", icon: "🧅", name: "Shalgam (Turnip)", audioText: "शलगम", color: "#E040FB" },
        { text: "ष", icon: "🛑", name: "Shatkon (Hexagon)", audioText: "षट्कोण", color: "#F44336" },
        { text: "स", icon: "🍊", name: "Santra (Orange)", audioText: "संतरा", color: "#FF9800" },
        { text: "ह", icon: "🐘", name: "Haathi (Elephant)", audioText: "हाथी", color: "#9E9E9E" },
        { text: "क्ष", icon: "⚔️", name: "Kshatriya (Warrior)", audioText: "क्षत्रिय", color: "#FF9800" },
        { text: "त्र", icon: "🔱", name: "Trishul (Trident)", audioText: "त्रिशूल", color: "#000000" },
        { text: "ज्ञ", icon: "🧘", name: "Gyani (Wise)", audioText: "ज्ञानी", color: "#FF9800" }
    ]
};
